In [1]:
import numpy as np

# We can create a numpy array by passing a list to the np.array function:

In [2]:
a = np.array([1, 2, 3])

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

# We can create a multi-dimensional array by passing a list of lists to the array function

In [5]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
type(matrix)

numpy.ndarray

In [11]:
matrix.size

9

In [12]:
matrix.shape

(3, 3)

# Referencing elements in numpy arrays at it's most basic is the same as referencing elements in Python lists.

In [13]:
a[0]

1

In [16]:
matrix[0]

array([1, 2, 3])

In [17]:
matrix[0][0]

1

In [18]:
print('a    == {}'.format(a))
print('a[0] == {}'.format(a[0]))
print('a[1] == {}'.format(a[1]))
print('a[2] == {}'.format(a[2]))

a    == [1 2 3]
a[0] == 1
a[1] == 2
a[2] == 3


# However, multidimensional numpy arrays are easier to index into. To obtain the element at the second column in the second row, we would write:

In [19]:
matrix[1, 1]

5

In [20]:
matrix[1][1]

5

In [21]:
matrix[2][2]

9

In [22]:
matrix[2][2] == matrix[2, 2]

True

# To get the first 2 elements of the last 2 rows: TBA

In [26]:
matrix[1:, :2]

array([[4, 5],
       [7, 8]])

# Arrays can also be indexed with a boolean sequence used to indicate which values should be included in the resulting array.

In [27]:
should_include_elements = [True, False, True]
a[should_include_elements]

array([1, 3])

# Note that the boolean sequence must the the same length as the array being indexed.

# Vectorized Operations

In [28]:
original_array = [1, 2, 3, 4, 5]
try:
    original_array + 1
except TypeError as e:
    print('An Error Occured!')
    print(f'TypeError: {e}')

An Error Occured!
TypeError: can only concatenate list (not "int") to list


In [29]:
type(original_array)

list

In [30]:
original_array = np.array(original_array)

In [31]:
original_array

array([1, 2, 3, 4, 5])

In [32]:
original_array + 1

array([2, 3, 4, 5, 6])

In [33]:
# Instead, we might write a for loop or a list comprehension:

In [34]:
original_array = [1, 2, 3, 4, 5]
array_with_one_added = []
for n in original_array:
    array_with_one_added.append(n + 1)
print(array_with_one_added)

[2, 3, 4, 5, 6]


In [35]:
original_array = [1, 2, 3, 4, 5]
array_with_one_added = [n + 1 for n in original_array]
print(array_with_one_added)

[2, 3, 4, 5, 6]


# This works the same way for the other basic arithmatic operators as well.

In [37]:
my_array = np.array([-3, 0, 3, 16])

print('my_array      == {}'.format(my_array))
print('my_array - 5  == {}'.format(my_array - 5))
print('my_array * 4  == {}'.format(my_array * 4))
print('my_array / 2  == {}'.format(my_array / 2))
print('my_array ** 2 == {}'.format(my_array ** 2))
print('my_array % 2  == {}'.format(my_array % 2))

my_array      == [-3  0  3 16]
my_array - 5  == [-8 -5 -2 11]
my_array * 4  == [-12   0  12  64]
my_array / 2  == [-1.5  0.   1.5  8. ]
my_array ** 2 == [  9   0   9 256]
my_array % 2  == [1 0 1 0]


# Not only are the arithmatic operators vectorized, but the same applies to the comparison operators

In [38]:
my_array = np.array([-3, 0, 3, 16])

print('my_array       == {}'.format(my_array))
print('my_array == -3 == {}'.format(my_array == -3))
print('my_array >= 0  == {}'.format(my_array >= 0))
print('my_array < 10  == {}'.format(my_array < 10))

my_array       == [-3  0  3 16]
my_array == -3 == [ True False False False]
my_array >= 0  == [False  True  True  True]
my_array < 10  == [ True  True  True False]


# Knowing what we know about indexing numpy arrays, we can use the comparison operators to select a certain subset of an array.

In [39]:
my_array[my_array > 0]

array([ 3, 16])

In [41]:
my_array[my_array%2 == 0]

array([ 0, 16])

In [42]:
print('1. my_array[my_array % 2 == 0]')
print('    - the original expression')
print('2. my_array[{} % 2 == 0]'.format(my_array))
print('    - variable substitution')
print('3. my_array[{} == 0]'.format(my_array % 2))
print('    - result of performing the vectorized modulus 2')
print('4. my_array[{}]'.format(my_array % 2 == 0))
print('    - result of comparing to 0')
print('5. {}[{}]'.format(my_array, my_array % 2 == 0))
print('    - variable substitution')
print('6. {}'.format(my_array[my_array % 2 == 0]))
print('    - our final result')

1. my_array[my_array % 2 == 0]
    - the original expression
2. my_array[[-3  0  3 16] % 2 == 0]
    - variable substitution
3. my_array[[1 0 1 0] == 0]
    - result of performing the vectorized modulus 2
4. my_array[[False  True False  True]]
    - result of comparing to 0
5. [-3  0  3 16][[False  True False  True]]
    - variable substitution
6. [ 0 16]
    - our final result


# Array Creation

In [43]:
np.random.randn(10)

array([ 0.75468563, -0.31357004,  0.45728561,  2.39573912,  0.11255802,
        0.13875326,  0.32056248,  1.4616774 , -0.45709673, -1.34555504])

In [44]:
a = np.random.randn(10)

In [45]:
a.mean()

0.16581581716457405

In [47]:
a.std()

1.091636911454493

In [48]:
np.random.randn(3, 4)

array([[-0.07399223, -0.77391865,  0.02461989,  1.71862166],
       [ 1.68647213, -0.48774411, -0.54915762,  1.22312794],
       [ 0.04602747, -1.19182476, -0.41290357,  0.71177598]])

# If we wish to draw from a normal distribution with mean 
# μ
# and standard deviation 
# σ
# , we'll need to apply some arithmetic. Recall that to convert from the standard normal distribution, we'll need to multiply by the standard deviation, and add the mean.

In [49]:
mu = 100
sigma = 30

sigma * np.random.randn(20) + mu

array([166.10840099,  56.86671993, 112.93634437,  79.10713044,
        87.78003644,  81.21482419,  49.96746366, 135.35734144,
        98.78938213, 130.13149158,  98.61806945, 185.29619233,
       119.48457061,  82.77926825, 102.59217751, 120.35832211,
        63.77397421,  99.72764816,  49.06342353, 137.690406  ])

# The zeros and ones functions provide the ability to create arrays of a specified size full or either 0s or 1s, and the full function allows us to create an array of the specified size with a default value.

In [50]:
print('np.zeros(3)    == {}'.format(np.zeros(3)))
print('np.ones(3)     == {}'.format(np.ones(3)))
print('np.full(3, 17) == {}'.format(np.full(3, 17)))

np.zeros(3)    == [0. 0. 0.]
np.ones(3)     == [1. 1. 1.]
np.full(3, 17) == [17 17 17]


In [52]:
np.zeros(3)

array([0., 0., 0.])

In [54]:
np.full(3, 4)

array([4, 4, 4])

# We can also use these methods to create multi-dimensional arrays by passing a tuple of the dimensions of the desired array, instead of a single integer value.

In [62]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

# Numpy's arange function is very similar to python's builtin range function. It can take a single argument and generate a range from zero up to, but not including, the passed number.

In [63]:
np.arange(5)

array([0, 1, 2, 3, 4])

# We can also specify a starting point for the range:

In [65]:
np.arange(1, 8)

array([1, 2, 3, 4, 5, 6, 7])

# As well as a step:

In [66]:
np.arange(1, 8, 2)

array([1, 3, 5, 7])

# Unlike python's builtin range, numpy's arange can handle decimal numbers

In [67]:
np.arange(1, 8, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5])

In [68]:
np.arange(1, 6.5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ])

In [69]:
np.arange(1, 5.5)

array([1., 2., 3., 4., 5.])

# The linspace method creates a range of numbers between a minimum and a maximum, with a set number of elements.

In [70]:
print('min: 1, max: 4, length = 4 -- {}'.format(np.linspace(1, 4, 4)))
print('min: 1, max: 4, length = 7 -- {} '.format(np.linspace(1, 4, 7)))

min: 1, max: 4, length = 4 -- [1. 2. 3. 4.]
min: 1, max: 4, length = 7 -- [1.  1.5 2.  2.5 3.  3.5 4. ] 


In [71]:
np.linspace(1, 2, 3)

array([1. , 1.5, 2. ])

In [72]:
np.linspace(1, 7, 7)

array([1., 2., 3., 4., 5., 6., 7.])

In [73]:
np.linspace(1, 7, 10)

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        , 5.66666667, 6.33333333, 7.        ])