# Exercises

# In your numpy-pandas-visualization-exercises repo, create a file named numpy_exercises.py for this exercise.

# Use the following code for the questions below:
















# 1. How many negative numbers are there?

In [1]:
import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [2]:
a<0

array([False, False, False, False,  True,  True, False, False, False,
        True, False,  True])

In [3]:
b = a[a<0]
b

array([-2, -1, -6, -7])

In [4]:
len(b)

4

# 2. How many positive numbers are there?

In [5]:
a>0

array([ True,  True,  True,  True, False, False, False, False, False,
       False,  True, False])

In [6]:
c = a[a>0]
c

array([ 4, 10, 12, 23,  3])

In [7]:
len(c)

5

# 3. How many even positive numbers are there?

In [8]:
c%2 == 0

array([ True,  True,  True, False, False])

In [9]:
d = c[c%2 == 0]
d


array([ 4, 10, 12])

In [10]:
len(d)

3

# 4. If you were to add 3 to each data point, how many positive numbers would there be?

In [11]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [12]:
e=a+3
e

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [13]:
f = e[e>0]
f

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3,  6])

In [14]:
len(f)

10

# 5. If you squared each number, what would the new mean and standard deviation be?

In [15]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [16]:
a.mean()

3.0

In [17]:
a.std()

8.06225774829855

In [18]:
g=a**2
g

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [19]:
g.mean()

74.0

In [20]:
g.std()

144.0243035046516

# 6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [21]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [22]:
a.mean()

3.0

In [23]:
b = a-3
b

array([  1,   7,   9,  20,  -5,  -4,  -3,  -3,  -3,  -9,   0, -10])

In [24]:
b.mean()

0.0

# 7. Calculate the z-score for each data point. Recall that the z-score is given by:

Z =(x−μ)/σ

In [25]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [26]:
m = a.mean() 
s = a.std()
m
s

8.06225774829855

In [27]:
z_score = (a-m)/s
z_score

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

# 8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

In [28]:
import numpy as np


# Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list



In [29]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [30]:
sum_of_a = a.sum()
sum_of_a

55

# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [31]:
min_of_a = a.min()
min_of_a

1

# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [32]:
max_of_a = a.max()
max_of_a

10

# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list



In [33]:
mean_of_a = a.mean()
mean_of_a

5.5

# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [34]:
product_of_a = np.product(a)
product_of_a

3628800

# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [35]:
squares_of_a = a**2
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [36]:
odds_in_a = a%2 != 0
odds_in_a
a[odds_in_a]

array([1, 3, 5, 7, 9])

# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [37]:
evens_in_a = a%2 == 0
evens_in_a
a[evens_in_a]

array([ 2,  4,  6,  8, 10])

# What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]



In [38]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]
b= np.array([
    [3, 4, 5],
    [6, 7, 8]
])
b

array([[3, 4, 5],
       [6, 7, 8]])

In [39]:
b.sum()

33

In [40]:
b.min()

3

In [41]:
b.max()

8

In [42]:
b.mean()

5.5

In [43]:
np.product(b)

20160

In [44]:
b**2

array([[ 9, 16, 25],
       [36, 49, 64]])

In [45]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. 
# **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

In [46]:
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
sum_of_b

33

In [47]:
b.sum()

33

In [48]:
# Exercise 2 - refactor the following to use numpy. 

min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1]) 

In [49]:
b.min()

3

In [50]:
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])
min_of_b

3

In [51]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.


In [52]:
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
max_of_b

8

In [53]:
b.max()

8

In [54]:

# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [55]:
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
mean_of_b

5.5

In [56]:
b.mean()

5.5

In [57]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number



In [58]:
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
product_of_b

20160

In [59]:
np.product(b)

20160

In [60]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

In [61]:
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
squares_of_b

[9, 16, 25, 36, 49, 64]

In [62]:
b**2

array([[ 9, 16, 25],
       [36, 49, 64]])

In [63]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

In [64]:
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
odds_in_b

[3, 5, 7]

In [65]:
b[b%2 != 0]

array([3, 5, 7])

In [66]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

In [67]:
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
evens_in_b

[4, 6, 8]

In [68]:
b[b%2 == 0]

array([4, 6, 8])

In [69]:
# Exercise 9 - print out the shape of the array b.

In [70]:
print(b.shape)

(2, 3)


In [71]:
# Exercise 10 - transpose the array b.
b.transpose()

array([[3, 6],
       [4, 7],
       [5, 8]])

In [72]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

np.reshape(b, (1,6))

array([[3, 4, 5, 6, 7, 8]])

# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [73]:
np.reshape(b, (6,1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [74]:
## Setup 3

c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]


c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9] ])

c


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.

In [75]:
c.min(), c.max(), c.sum(), np.product(c)

(1, 9, 45, 362880)

# Exercise 2 - Determine the standard deviation of c.

In [76]:
c.std()

2.581988897471611

# Exercise 3 - Determine the variance of c.

In [77]:
c.var()

6.666666666666667

# Exercise 4 - Print out the shape of the array c

In [78]:
c.shape

(3, 3)

# Exercise 5 - Transpose c and print out transposed result.

In [79]:
c.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Exercise 6 - Get the dot product of the array c with c.

In [80]:
np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261


In [81]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
d =c.transpose()
d

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [83]:
e = c*d
e

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [84]:
e.sum()

261

# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.


In [85]:
np.product(e)

131681894400

In [86]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
])

d


array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [87]:
# Exercise 1 - Find the sine of all the numbers in d


In [88]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [89]:

# Exercise 2 - Find the cosine of all the numbers in d

In [90]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [91]:
# Exercise 3 - Find the tangent of all the numbers in d

In [92]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [93]:
# Exercise 4 - Find all the negative numbers in d

In [94]:
d[d<0]

array([-90, -30, -45, -45])

In [95]:
# Exercise 5 - Find all the positive numbers in d

In [96]:
d[d>0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [97]:
# Exercise 6 - Return an array of only the unique numbers in d.

In [98]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [99]:
# Exercise 7 - Determine how many unique numbers there are in d.

In [100]:
len(np.unique(d))

11

In [101]:
# Exercise 8 - Print out the shape of d.

In [102]:
d.shape

(3, 6)

In [103]:
# Exercise 9 - Transpose and then print out the shape of d.

In [104]:
e = d.transpose()
e

array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

In [105]:
e.shape

(6, 3)

In [106]:
# Exercise 10 - Reshape d into an array of 9 x 2

In [107]:
np.reshape(d, (9, 2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])