# Creating array out of list

In [2]:
import numpy as np
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a[0]

1

In [5]:
matrix[1]

array([4, 5, 6])

In [6]:
matrix[1][1]

5

In [7]:
print('a    == {}'.format(a))
print('a[0] == {}'.format(a[0]))
print('a[1] == {}'.format(a[1]))
print('a[2] == {}'.format(a[2]))

a    == [1 2 3]
a[0] == 1
a[1] == 2
a[2] == 3


In [8]:
matrix[1, 1]

5

In [13]:
matrix[1:, :2,]

array([[4, 5],
       [7, 8]])

In [14]:
should_include_elements = [True, False, True]
a[should_include_elements]

array([1, 3])

In [15]:
should_include_elements = [True, True, False]
a[should_include_elements]

array([1, 2])

In [16]:
original_array = [1, 2, 3, 4, 5]
try:
    original_array + 1
except TypeError as e:
    print('An Error Occured!')
    print(f'TypeError: {e}')

An Error Occured!
TypeError: can only concatenate list (not "int") to list


In [17]:
original_array = [1, 2, 3, 4, 5]
original_array + 1

TypeError: can only concatenate list (not "int") to list

In [19]:
original_array = [1, 2, 3, 4, 5]

new_array = []

for item in original_array:
    new_array.append(item + 1)


In [20]:
new_array

[2, 3, 4, 5, 6]

In [22]:
original_array = [1, 2, 3, 4, 5]
array_with_one_added = [n + 1 for n in original_array]
array_with_one_added

[2, 3, 4, 5, 6]

In [23]:
original_array = np.array([1, 2, 3, 4, 5])
original_array + 1

array([2, 3, 4, 5, 6])

In [24]:
my_array = np.array([-3, 0, 3, 16])

print('my_array      == {}'.format(my_array))
print('my_array - 5  == {}'.format(my_array - 5))
print('my_array * 4  == {}'.format(my_array * 4))
print('my_array / 2  == {}'.format(my_array / 2))
print('my_array ** 2 == {}'.format(my_array ** 2))
print('my_array % 2  == {}'.format(my_array % 2))

my_array      == [-3  0  3 16]
my_array - 5  == [-8 -5 -2 11]
my_array * 4  == [-12   0  12  64]
my_array / 2  == [-1.5  0.   1.5  8. ]
my_array ** 2 == [  9   0   9 256]
my_array % 2  == [1 0 1 0]


In [25]:
my_array**3

array([ -27,    0,   27, 4096])

In [26]:
my_array = np.array([-3, 0, 3, 16])

print('my_array       == {}'.format(my_array))
print('my_array == -3 == {}'.format(my_array == -3))
print('my_array >= 0  == {}'.format(my_array >= 0))
print('my_array < 10  == {}'.format(my_array < 10))

my_array       == [-3  0  3 16]
my_array == -3 == [ True False False False]
my_array >= 0  == [False  True  True  True]
my_array < 10  == [ True  True  True False]


In [27]:
my_array == -3

array([ True, False, False, False])

In [28]:
my_array >= 0

array([False,  True,  True,  True])

In [29]:
my_array<10

array([ True,  True,  True, False])

In [30]:
my_array[my_array == -3]

array([-3])

In [31]:
my_array[my_array >= 0]

array([ 0,  3, 16])

In [32]:
my_array[my_array<10]

array([-3,  0,  3])

In [33]:
my_array%2 == 0

array([False,  True, False,  True])

In [34]:
my_array[my_array%2 == 0]

array([ 0, 16])

In [40]:
np.random.randn(10)

array([ 1.29386364,  0.10831193,  1.21575393, -0.47514694,  0.58627494,
        0.77025539, -0.780507  ,  0.78409744,  2.01305512,  0.34697714])

In [39]:
np.random.randn(3, 4)

array([[ 2.41653047,  0.32292129, -0.16423357,  0.82860284],
       [ 0.38912787, -0.10363737, -0.01567048,  0.25814902],
       [-0.2119003 , -0.29589436,  1.28765651, -0.78181953]])

In [41]:
print('np.zeros(3)    == {}'.format(np.zeros(3)))
print('np.ones(3)     == {}'.format(np.ones(3)))
print('np.full(3, 17) == {}'.format(np.full(3, 17)))

np.zeros(3)    == [0. 0. 0.]
np.ones(3)     == [1. 1. 1.]
np.full(3, 17) == [17 17 17]


In [42]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [44]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [45]:
np.full(9, 7)

array([7, 7, 7, 7, 7, 7, 7, 7, 7])

In [46]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
np.arange(4)

array([0, 1, 2, 3])

In [49]:
b=range(4)
for i in b:
    print(i)

0
1
2
3


In [50]:
np.arange(1, 4)

array([1, 2, 3])

In [51]:
np.arange(1, 4, 2)

array([1, 3])

In [52]:
np.arange(1, 4, .25)

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 ,
       3.75])

In [53]:
print('min: 1, max: 4, length = 4 -- {}'.format(np.linspace(1, 4, 4)))
print('min: 1, max: 4, length = 7 -- {} '.format(np.linspace(1, 4, 7)))

min: 1, max: 4, length = 4 -- [1. 2. 3. 4.]
min: 1, max: 4, length = 7 -- [1.  1.5 2.  2.5 3.  3.5 4. ] 


# 2 Questions TBA